### PR TITLE
adds macOS support

### PR DESCRIPTION
**Pull request by bucanero**
Adds support for macOS Mojave (10.14.6)

After installing the required libs/tools using [brew](https://brew.sh) in a macOS Mojave environment, some of the check-dependencies scripts required a fix to validate the installation paths properly.

### CODE REVIEW

**Comment by miigotu** [comment]
Why are you adding licences and badges and build workflows in the same PR as a build fix for Mac?

**Comment by bucanero** [comment]
> Why are you adding licences and badges and build workflows in the same PR as a build fix for Mac?

I totally forgot about this PR, it looks like I submitted it a long time ago.
Now I did some updates on my master branch, and ended up here too.

**Comment by miigotu** [comment]
This is why you should not make PR's from your master branch =P

**Comment by bucanero** [comment]
yes, you're right, I'm still learning about these process details with Git. Feel free to remove or close  if needed.

**Comment by miigotu** [comment]
If you can, please rebase, resolve conflicts, and separate unrelated changes into separate PR's

**Comment by bucanero** [comment]
> If you can, please rebase, resolve conflicts, and separate unrelated changes into separate PR's

alright, I'll try to make a new PR, including only the changes to build on macOS. Hopefully I'll figure out how to do it properly with my git client.

**Comment by bucanero** [comment]
Moved to PR #88

**Pull request closed without merging**
