### PR TITLE
Update GCC to 7.2.0

### PR DESCRIPTION
**Pull request by bgK**
All the samples from PSL1GHT I've tested work, including the SPU ones. I've also successfully tested ScummVM with this version.

The changes from this pull request are required: https://github.com/ps3dev/PSL1GHT/pull/68

### CODE REVIEW

**Comment by xerpi** [comment]
@bgK Does the current newlib build fine with GCC 7.2.0? I had to do [this](https://github.com/xerpi/ps3toolchain/commit/8d71e37c1ba142008abd5651dbd5dd5a9560301d) change in order to manage to get newlib compiling.

**Comment by bgK** [comment]
@mirh because the ppu config file is very hacky

@xerpi yes, the current newlib builds fine with this patch

**Comment by xerpi** [comment]
Ah, it must be that `newlib-stdint.h` needs to be added for the newer versions of newlib.

**Comment by bgK** [comment]
This one has more changes because I took the PPC64 Linux config file and reapplied the changes for the PPU/GameOS. Some things had changed names since the GCC 4 days.

I don't care which one gets merged, as long as one gets in!

**Pull request merged**
